apiVersion: v1alpha
kind: cypress
sauce:
  region: eu-central-1 # or us-west-1
  concurrency: 3
  metadata:
    name: Cypress Cross Browser tests
    tags:
      - cypress
      - cross-browser
    build: "Cypress: Cross Browser - $DATE"
docker:
  fileTransfer: mount
cypress:
  version: 7.3.0
  configFile: "cypress.json"  # We determine related files based on the location of the config file.
suites:
  # Chrome v91
  - name: "Swag Labs Login Chrome 91"
    browser: "chrome"
    browserVersion: "91.0"
    platformName: "Windows 10"
    screenResolution: "1400x1050"
    config:
      testFiles: [ "**/login.*" ]
  # chrome 85
  - name: "Swag Labs Login chrome 85"
    browser: "chrome"
    browserVersion: "85.0"
    platformName: "Windows 10"
    screenResolution: "1400x1050"
    config:
      testFiles: [ "**/login.*" ]
  # chrome 76
  - name: "Swag Labs Login chrome 76"
    browser: "chrome"
    browserVersion: "76.0"
    platformName: "Windows 10"
    screenResolution: "1400x1050"
    config:
      testFiles: [ "**/login.*" ]
