# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

# multiple pipelines can re-use variables that are stored in a variable group
variables:
- group: sauce-labs-variables

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
  
- script: |
    cd ./webdriverio/webdriver/examples/w3c/
    npm install
    npm run test.saucelabs.us -- --logLevel "debug"
  env: 
    SAUCE_USERNAME: $(sauceUsername) #this will read the value from 'sauceUsername' in ADO and will store it into SAUCE_USERNAME env variable
    SAUCE_ACCESS_KEY: $(sauceAccessKey)
  displayName: 'install and run WebdriverIO tests in Sauce Labs'
