# We are using parallel jobs here

aliases:
  - &prepare_environment
    working_directory: ~/repo
    docker:
      - image: circleci/node:dubnium  # primary container for the build job
    steps:
      - checkout
      - run:
          name: "Update NPM"
          command: |
            sudo npm install -g npm@latest

version: 2
workflows:
  version: 2
  build:
    jobs:
      - notRecommended
      - testcafe
      - webdriverio

jobs:
  # Not recommended frameworks like NightWatch and Protractor
  notRecommended:
    steps:
      - *prepare_environment
      - run:
          name: "Update NPM"
          command: |
            sudo npm install -g npm@latest
      - run:
          name: "Run Nightwatch Webdriver"
          command: |
            cd nightwatch/webdriver/examples/update-sauce
            npm install
            npm run test.saucelabs.us
      - run:
          name: "Run Protractor Best Practices"
          command: |
            cd protractor/selenium/best-practices
            npm install
            npm run test.saucelabs.us
  # Testcafe takes pretty long due to the sauce connect tunnel
  testcafe:
    steps:
      - *prepare_environment
      - run:
          name: "Update NPM"
          command: |
            sudo npm install -g npm@latest
      - run:
          name: "Run TestCafe Best Practices"
          command: |
            cd testcafe/best-practices
            npm install
            npm run test.saucelabs.us
  # WebdriverIO headless and best practices
  webdriverio:
    steps:
      - *prepare_environment
      - run:
          name: "Update NPM"
          command: |
            sudo npm install -g npm@latest
      - run:
          name: "Run WebdriverIO Headless"
          command: |
            cd webdriverio/webdriver/examples/headless
            npm install
            npm run test.saucelabs.headless
      - run:
          name: "Run WebdriverIO Best Practices"
          command: |
            cd webdriverio/webdriver/best-practices
            npm install
            npm run test.saucelabs.us -- --maxInstances=25
